config/routes.rb
Rails.application.routes.draw do
  resources :trips

  root 'trips#index'

end

app/models/trip.rb
class Trip < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  def index
    @trips = Trip.all
  end

  def show
  end

  def new
    @trip = Trip.new
  end

  def edit
  end

  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to trips_path, notice: 'Trip was successfully created.' }
        format.json { render :index, status: :created}
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title TripTracker
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    = csrf_meta_tags
  body
    .wrapper
      header
        .navbar
          .navbar-inner
            .container
              ul.nav.nav-tabs
                li
                  =link_to("Home", root_path)
                li.dropdown
                  a.dropdown-toggle(data-toggle="dropdown" data-target="#")
                    | Trips
                    b.caret
                  ul.dropdown-menu(role="menu" aria-labelledby="dLabel")
                    li()
                      = link_to("New Trip", new_trip_path)
      
      section.main
        = yield  

app/views/trips/_form.html.erb
<%= form_for @trip, :html => { :class => "form-horizontal trip" } do |f| %>

    <% if @trip.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @trip.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@trip[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@trip[:description]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            trips_path, :class => 'btn btn-default' %>

<% end %>

app/views/trips/_trip.html.slim
tr()
  td() = trip.name
  td() = trip.description
  td() &nbsp;

app/views/trips/index.html.slim
.container
  .row-fluid
    .col-md-10
      h3() List of all Trips
    .col-md-2.pull-right
      = link_to("New Trip", new_trip_path)
  .row-fluid
    table.table.table-responsive
      tr()
        th() Name
        th() Description
        th() Actions
      tbody
        = render @trips
          

app/views/trips/new.html.erb
<div class="container">
  
  <%- model_class = Trip -%>
  <div class="page-header">
    <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
  </div>
  <%= render :partial => 'form' %>
</div>